### PR TITLE
feat: use https if configured

### PR DESCRIPTION
**Pull request by aaronjensen**

### CODE REVIEW

**Comment by betaboon** [comment]
thank you for the contribution. and sorry for the holdup.

**Comment by aaronjensen** [comment]
Thank you for the merge! If you wouldn't mind leaving a note once it's published I'd appreciate it so we can update things on our end.

**Comment by betaboon** [comment]
@aaronjensen i just transferred the repo and npm-package to my github-org and integrated ci.
so this package now uses semantic-release to auto-publish on merge.

the content of this pr should not be part of v0.1.0

**Comment by aaronjensen** [comment]
Ah, great, thank you!

**Pull request merged**
